stages:
  check_updated:
    # check that generated file and the one in repo are same
    cmd: ./gen.py | diff schema.json -
    deps:
      - schema.json
  generate:
    cmd: ./gen.py > schema.json
    deps:
      - gen.py
    outs:
      - schema.json:
          cache: false
          persist: true
  tests:
    cmd: pytest -vv tests.py
    deps:
      - schema.json
