[tool.black]
line-length = 79

[tool.isort]
profile = "black"
line_length = 79

[tool.pytest.ini_options]
addopts = "-ra -vv"
testpaths = "tests.py"

[tool.ruff.lint]
ignore = ["D", "FA", "FBT"]
select = ["ALL"]
