stages:
  copy_multiple:
    cmd: cp foo bar && cp foo1 bar1 && cp foo2 bar2
    deps:
      - foo
      - foo1
    outs:
      - foo1
      - bar1:
          cache: false
      - bar2:
          persist: true
      - bar3:
          checkpoint: true
      - bar4:
          desc: "bar4"
          labels:
          - label1
          - label2
          type: type1
          meta:
            key: value
            key1: value1
      - bar5:
          remote: remote1
      - bar6:
          push: false
    live:
      foo:
        summary: true
        html: true
        cache: false
