stages:
  use-params_stage:
    cmd: cat params.yaml > params2.yaml
    params:
      - auc
      - loss
    outs:
      - params2.yaml
  use-custom-params_file:
    cmd: cat my_params.yaml > params2.yaml
    params:
      - my_params.yaml:
          - auc
          - loss
    outs:
      - params2.yaml
  use-full-params_file:
    cmd: cat full_file.yaml > params2.yaml
    params:
      - my_params.yaml:
    outs:
      - params2.yaml