stages:
  copy_multiple:
    cmd: cp foo bar && cp foo1 bar1 && cp foo2 bar2
    deps:
      - foo
      - foo1
    outs:
      - foo1
      - bar1:
          cache: false
      - bar2:
          persist: true
      - bar3:
          checkpoint: true
      - bar4:
          desc: "bar4"
    live:
      foo:
        summary: true
        html: true
