plots:
  ROC: # Combine multiple data sources.
    x: fpr
    extra: 3

stages:
  stage_one:
    cmd: python train.py input plots
    deps:
      - input
    plots:
      - plot1
      - plot2:
          cache: true
          extra: false
