# This workflow will install DVC, and run some validations for the schema dependencies.

name: Python application

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install DVC
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate schema, validate it's not stale, and verify
        run: |
          ./gen.py | diff schema.json -
          ./gen.py > schema.json
          ./tests.py
          dvc repro  # sanity check
