name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '5 1 * * *'  # every day at 01:05
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install requirements
        run: |
          pip install --upgrade pip wheel
          pip install -r requirements.txt

      - name: Run pylint
        run: pylint gen.py tests.py

      - name: Generate schema, validate it's not stale, and verify with tests
        run: |
          ./gen.py | diff schema.json -
          ./gen.py > schema.json
          pytest

      - name: Sanity check with dvc
        continue-on-error: true
        run: |
          pip install "dvc @ git+https://github.com/iterative/dvc"
          dvc repro
