# This workflow will install DVC, and run some validations for the schema dependencies.

name: Python application

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install DVC
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade "dvc>=1.0.0b3"
      - name: Run Tests
        run: dvc repro
        env:
          HYPOTHESIS_PROFILE: ci
